### ISSUE TITLE
Bug when disconnect

### ISSUE THREAD

**Issue by Brokeos** [Inkzzz/ArmorEvent#3]
Hi,

I found a bug, when a player disconnect with armor the event doesn't work.

Can  you fix it ?

**Comment by Inkzzz** [comment]
What version of Spigot do you use?

**Comment by Brokeos** [comment]
I use 1.7, But after the last update it work.

**Comment by Brokeos** [comment]
(And I fix the problem for the dispenser in 1.7 too)
